### ISSUE TITLE
After loading the Docker image from OSF for (Valavi et al. 2023), when I am trying to connect to the RStudio from container am getting "RStudio Initializing Error"

### ISSUE THREAD

**Issue by Melagiris** [rvalavi/SDM-Spatial-Validation#1]
Dear @rvalavi, I was trying for the given ensemble approach https://onlinelibrary.wiley.com/doi/full/10.1111/geb.13639

But after loading the Docker image from OSF repository which stores the code and Appendix S1, when I am trying to connect to the RStudio from container am getting "RStudio Initializing Error". Attached screenshot for your reference.

<img width="1261" alt="Screenshot 2023-02-13 at 00 59 53" src="https://user-images.githubusercontent.com/39184822/218402160-bc5a5090-c0e9-4c05-8554-3116e63581c3.png">

<img width="1512" alt="Screenshot 2023-02-13 at 00 53 11" src="https://user-images.githubusercontent.com/39184822/218402188-7006bb25-94cb-4d6d-94b3-0f67d3bf56a4.png">

**Comment by rvalavi** [comment]
Are you using a Mac with M1/M2 cpu? 

Try building the Docker image;

You don't have to make the docker image; you can just use the code in OSF..

**Comment by Melagiris** [comment]
Dear @rvalavi ,

Yes, I am using the Mac with M1 chip.

Did you mean the below line of code from OSF?:
docker build -t rvalavi:4.0

And what all files do I need to download from OSF before running the above line of code in terminal?

Thanks,
Rahul

**Comment by rvalavi** [comment]
Sorry for the late reply. 
I assume the typical docker images are not compatible with Mac M1. I don't have an M1 machine to try it out. You can have a look and if it is the case, you just need to use an appropriate docker image of RStudio with R v.4 and build the image yourself (based on the code provided in the appendix).

https://osf.io/g6dc3/?view_only=2f91390cb8f14ae3ba75c35427e017e4

![image](https://user-images.githubusercontent.com/30306220/221471373-6771ee63-2275-437a-91d5-aee65e77b094.png)
